Create scan.yml
Fix "vfsoverlay" file not found issue by removing clean. WIP: testing removing archive instead.

java.lang.IllegalStateException: "vfsoverlay" file used during build doesn't exist, please make sure you are not cleaning build files before launching the analysis. The missing file: /Users/runner/Library/Developer/Xcode/DerivedData/Blink-elthxnvkeejvojbingnmbxlyaapj/Build/Intermediates.noindex/ArchiveIntermediates/Blink/IntermediateBuildFilesPath/MBProgressHUD.build/Debug-iphoneos/MBProgressHUD Framework.build/all-product-headers.yaml